small99/deeptest

第一期/成都-MFC/debug/hello_vs.py, 第一期/成都-MFC/task001/Calc.py, 第一期/成都-MFC/task001/MySort.py, 第一期/成都-MFC/task001/testCalc.py
=> finish task001

第一期/北京-菜鸟渣渣/random_data.py, 第一期/北京-菜鸟渣渣/readme.xml
replaceAll=alt+shift+R
查看doc = shift+f3
重构 = alt +shift +L
匹配两个链接行 = ctrl+shift+j
=> 新增随机数生成文件和说明性文件

第一期/北京-Windy/sample1.py, 第一期/北京-Windy/sample2.py, 第一期/北京-Windy/sample3.py, 第一期/北京-Windy/sample4.py
=> subm the yesterday code

第一期/无锡-慕兮/TASK2/day3.py
=> add day3.py

第一期/广州-33/0112整理PyCharm使用笔记.md
=> 上传1月12日学习日志

第一期/无锡-慕兮/TASK2/day4.py
=> add day4.py

第一期/北京-Windy/sample5.py
=> submit sample5-0113

第一期/上海-辰雨/第二次/Class.py, 第一期/上海-辰雨/第二次/Function.py, 第一期/上海-辰雨/第二次/Loop Control.py, 第一期/上海-辰雨/第二次/iterable.py, 第一期/上海-辰雨/第二次/mould_package.py, 第一期/上海-辰雨/第二次/operation_excel.py, 第一期/上海-辰雨/第二次/operator_date_time.py, 第一期/上海-辰雨/第二次/operator_file.py, 第一期/上海-辰雨/第二次/operator_json.py, 第一期/上海-辰雨/第二次/read_ini.py
=> Exercise Code

第一期/广州-33/快学python3示例练习代码/annotation.py, 第一期/广州-33/快学python3示例练习代码/cmd_args.py, 第一期/广州-33/快学python3示例练习代码/demo.py, 第一期/广州-33/快学python3示例练习代码/input_data_split.py, 第一期/广州-33/快学python3示例练习代码/transform.py, 第一期/广州-33/快学python3示例练习代码/useInput.py
=> 提交今日快学python3示例练习的代码

第一期/无锡-慕兮/TASK2/day5.py
=> add day5.py

第一期/成都-MFC/task002/abyteofpython/module_using_name.py, 第一期/成都-MFC/task002/abyteofpython/module_using_sys.py, 第一期/成都-MFC/task002/abyteofpython/str_foramt.py, 第一期/成都-MFC/task002/kuaixuepython3/python3_class.py, 第一期/成都-MFC/task002/kuaixuepython3/python3_forloop.py, 第一期/成都-MFC/task002/kuaixuepython3/python3_function.py, 第一期/成都-MFC/task002/kuaixuepython3/python3_function2.py, 第一期/成都-MFC/task002/kuaixuepython3/python3_nested.py
add: backup_ver1 and python3 demo.
=> add: backup_ver1 and python3 demo.

第一期/无锡-慕兮/TASK2/day1_bu.py, 第一期/无锡-慕兮/TASK2/day2_bu1.py, 第一期/无锡-慕兮/TASK2/day2_bu2.py, 第一期/无锡-慕兮/TASK2/day6.py
=> add 4 new files

第一期/无锡-慕兮/TASK2/day3_bu.py
=> add day3_bu.py

第一期/北京-Windy/sample6.py, 第一期/北京-Windy/sample7.py, 第一期/北京-Windy/sample8.py
=> submit code-0115

第一期/北京-Windy/sample8.py
=> resubmit sample8-0115

第一期/北京-Windy/0116学习python心得.md, 第一期/北京-Windy/sample10.py, 第一期/北京-Windy/sample8.py, 第一期/北京-Windy/sample9.py
=> submit code 0116

第一期/无锡-慕兮/TASK2/book.csv, 第一期/无锡-慕兮/TASK2/http_urllib.py, 第一期/无锡-慕兮/TASK2/test.xml, 第一期/无锡-慕兮/TASK2/test_new.xml, 第一期/无锡-慕兮/TASK2/xml_module.py, 第一期/无锡-慕兮/TASK2/xml_xpath.py
=> day8 commit

第一期/北京-Windy/sample12.py, 第一期/北京-Windy/sample13.py, 第一期/北京-Windy/sample14.py
=> submit code 0118

第一期/北京-nancy/task2/list.py, 第一期/北京-nancy/task2/tuple.py
=> add list.py and tuple.py

第一期/北京-nancy/task2/dic.py
=> add dic.py

第一期/北京-Windy/sample15.py, 第一期/北京-Windy/sample16.py, 第一期/北京-Windy/sample17.py
=> submit code 0120

第一期/广州-Aimee/homework1.py, 第一期/广州-Aimee/homework2-1.py, 第一期/广州-Aimee/homework2.py, 第一期/广州-Aimee/iniConfig.ini, 第一期/广州-Aimee/lesson01.py, 第一期/广州-Aimee/lesson02.py, 第一期/广州-Aimee/lesson03.py, 第一期/广州-Aimee/lesson04.py, 第一期/广州-Aimee/lesson05_iter.py, 第一期/广州-Aimee/lesson06_int.py, 第一期/广州-Aimee/lesson07_path os.py
=> the first commit

第一期/上海-辰雨/第二次/InsertionSort.py, 第一期/上海-辰雨/第二次/OperationPyMySQL.py, 第一期/上海-辰雨/第二次/OperatorCrawler.py, 第一期/上海-辰雨/第二次/QuickSort.py, 第一期/上海-辰雨/第二次/SelectionSort.py, 第一期/上海-辰雨/第二次/SendEmail.py
=> Sort algorithm

第一期/北京-Windy/2018-1-23 总结.md, 第一期/北京-Windy/Perfect Square.py, 第一期/北京-Windy/arithmetic.py, 第一期/北京-Windy/array.py, 第一期/北京-Windy/insert.py, 第一期/北京-Windy/new_sushu.py, 第一期/北京-Windy/reverse.py, 第一期/北京-Windy/salary.py, 第一期/北京-Windy/sort_0123.py, 第一期/北京-Windy/sort_three.py, 第一期/北京-Windy/square.py, 第一期/北京-Windy/sushu.py, 第一期/北京-Windy/zhiyinshu.py
=> submit  code 0123

第一期/北京-Windy/Pascal's triangle;.py, 第一期/北京-Windy/sort_0124.py
=> submit code 0124

第一期/上海-辰雨/第二次/Class(First).py, 第一期/上海-辰雨/第二次/Decorate(one).py, 第一期/上海-辰雨/第二次/DouBanMovie.py, 第一期/上海-辰雨/第二次/try...except.py
=> try...except

第一期/无锡-慕兮/Task3/day_2/json_parse.py, 第一期/无锡-慕兮/Task3/day_2/json_parse_common.py, 第一期/无锡-慕兮/Task3/day_2/json_tem.json, 第一期/无锡-慕兮/Task3/day_2/json_temp.json
=> add Task3 day2 files“

第一期/上海-棒棒糖/第三次任务-python接口测试/第三天/Yahoo_weather_data.xml, 第一期/上海-棒棒糖/第三次任务-python接口测试/第三天/xml_test.py, 第一期/上海-棒棒糖/第三次任务-python接口测试/第三天/xml_write_data.xml, 第一期/上海-棒棒糖/第三次任务-python接口测试/第三天/xml_xpath_test.py, 第一期/上海-棒棒糖/第二次任务-每日代码练习/1-30/XML_test.py, 第一期/上海-棒棒糖/第二次任务-每日代码练习/1-30/Yahoo_weather_SAX.py, 第一期/上海-棒棒糖/第二次任务-每日代码练习/1-30/itertools_test.py, 第一期/上海-棒棒糖/第二次任务-每日代码练习/1-30/test1.py, 第一期/上海-棒棒糖/第二次任务-每日代码练习/1-30/test2.py, 第一期/上海-棒棒糖/第二次任务-每日代码练习/1-30/test3.py, 第一期/上海-棒棒糖/第二次任务-每日代码练习/1-30/yahooweather.xml
=> 1-31代码练习&第三次任务第三天提交

第一期/上海-辰雨/第二次/Class(Four).py, 第一期/上海-辰雨/第二次/Class(Second).py, 第一期/上海-辰雨/第二次/Class(Third).py, 第一期/上海-辰雨/第二次/Crawler_One.py, 第一期/上海-辰雨/第二次/VariableParameter.py
=> VariableParameter

第一期/广州_Cc果冻_龄/009setTest.py, 第一期/广州_Cc果冻_龄/010ifTest.py, 第一期/广州_Cc果冻_龄/011forTest.py, 第一期/广州_Cc果冻_龄/012whileTest.py, 第一期/广州_Cc果冻_龄/013defTest.py
=> 提交任务20180202-增加循环及函数部分代码练习

第一期/上海-棒棒糖/第二次任务-每日代码练习/2017-2/web实战/awesome-python3-webapp/www/apis.py, 第一期/上海-棒棒糖/第二次任务-每日代码练习/2017-2/web实战/awesome-python3-webapp/www/app.py, 第一期/上海-棒棒糖/第二次任务-每日代码练习/2017-2/web实战/awesome-python3-webapp/www/coroweb.py, 第一期/上海-棒棒糖/第二次任务-每日代码练习/2017-2/web实战/awesome-python3-webapp/www/models.py, 第一期/上海-棒棒糖/第二次任务-每日代码练习/2017-2/web实战/awesome-python3-webapp/www/orm.py, 第一期/上海-棒棒糖/第二次任务-每日代码练习/2017-2/web实战/awesome-python3-webapp/www/test.py
=> 第二次任务-web搭建

第二期/广州-dabral/calculator.py, 第二期/广州-dabral/sort.py
=> mission1-1 complete calculator.py

第一期/广州-遥远/01.py, 第一期/广州-遥远/02.py
=> 广州-遥远第一次任务

第二期/北京-辉色秋天/day-2/day2-2-class.py, 第二期/北京-辉色秋天/day-2/day2-2-generate.py, 第二期/北京-辉色秋天/day-2/day2-4-init.py, 第二期/北京-辉色秋天/day-2/day2-4-os.py, 第二期/北京-辉色秋天/day-2/day2-forwhile.py, 第二期/北京-辉色秋天/day-2/day2-function.py, 第二期/北京-辉色秋天/day-2/day2-if.py
=> task2-day2 completed

第二期/北京-辉色秋天/day-2/data_demo-1.xml, 第二期/北京-辉色秋天/day-2/data_demo.xml, 第二期/北京-辉色秋天/day-2/day2-5-json.py, 第二期/北京-辉色秋天/day-2/day2-5-time-1.py, 第二期/北京-辉色秋天/day-2/day2-5-time.py, 第二期/北京-辉色秋天/day-2/day2-6-urllib.py, 第二期/北京-辉色秋天/day-2/day2-6-xml.py
=> task2-5 complete
